server:
    port: 9098
cloud:
    aws:
        access_key_id: AKIAZHED6K4JKULV5XPN
        secret_access_key: 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
        s3:
            bucket: mycareerbucket
            region: us-west-1
        ec2:
            region: us-west-1
logging:
    file: C:\Users\palas\OneDrive\Desktop\app.log